#! /user/bin/python3
import pandas as pd
df =pd.read_csv('./interview_data_set',error_bad_lines=False,names =['res'])
df['res_new'] = df['res'].apply(lambda x: x.find('error'))
df = df[df['res_new']!=-1]
def slove_name(x):
x = x.split(' ')
x = x[3]
return x
def slove_time(x):
x = x.split(' ')
x = x[2]
x = x.split(':')
x1 = x[0]
x2 = int(x[0])+1
if x2<10:
x2 = '0'+str(x2)
if x2==25:
x2 = '00'
return str(x[0])+'00-'+str(x2)+'00'
def slove_pid(x):
x = x.split('])')[0].split('[')[-1]
return x
def slove_pid(x):
x = x.split('])')[0].split('[')[-1]
return x
def slove_error(x):
x = x.split(']):')[-1]
return x
global n
df['time'] = df['res'].apply(lambda x:slove_time(x))
df['name'] = df['res'].apply(lambda x:slove_name(x))
df['pid'] = df['res'].apply(lambda x:slove_pid(x))
df['error'] = df['res'].apply(lambda x:slove_error(x))
df[['time','name','pid','error']].to_csv('res.txt',index=False,header=None)



import requests                                                   #导入模块
import json                                                       #导入模块

url = 'https://foo.com/bar'                                       #需要上传的地址
rdata = {
      "deviceName": "BBAOMACBOOKAIR2",                            #设备名称
      "processId": "78",                                          #错误的进程号码
      "processName": "Undefined error",                           #进程/服务名称
      "description":" Could not find uid associated with service",#错误的原因（描述）
      "timeWindow":"Every hour",                                  #发生的时间（小时级）
      "numberOfOccurrence":"15",                                  #在小时级别内发生的次数
}
headers = {'content-type': 'application/json',}                   #定制表头

ret = requests.post(url,data=json.dumps(rdata),headers=headers)   #按照格式上传

print(ret.text)
